### ISSUE TITLE
S2I image jboss-decisionserver63-openshift:1.3  error

### ISSUE THREAD

**Issue by jainmnsh** [jboss-openshift/openshift-quickstarts#83]
I am trying to build S2I using  jboss-decisionserver63-openshift:1.3 IS but getting following error when trying pull kieserver-pull:jar:1.0.0 hence this issue.

[INFO] Total time: 7.347 s
--
  | [INFO] Finished at: 2018-05-16T21:34:28+00:00
  | [INFO] Final Memory: 13M/81M
  | [INFO] ------------------------------------------------------------------------
  | [WARNING] The requested profile "openshift" could not be activated because it does not exist.
  | [ERROR] Failed to execute goal on project kieserver-pull: Could not resolve dependencies for project org.openshift:kieserver-pull:jar:1.0.0.Final: Could not find artifact projects:jar:0.0.1-SNAPSHOT in central (https://repo1.maven.org/maven2 ) -> [Help 1]
  | org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project kieserver-pull: Could not resolve dependencies for project org.openshift:kieserver-pull:jar:1.0.0.Final: Could not find artifact projects:jar:0.0.1-SNAPSHOT in central (https://repo1.maven.org/maven2 )
  | at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
  | at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
  | at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)

**Comment by spolti** [comment]
Hey there, note that the decisionserver63 image are deprecated, use the 64 instead (registry.access.redhat.com/jboss-decisionserver-6/decisionserver64-openshift:1.3).

**Comment by jainmnsh** [comment]
thanks. I don't have "decisionserver64-openshift:1.3" in our openshift env. I will request to add the image in our environment but I am using decisionserver64-openshift:latest tag and still below error.
[ERROR] Failed to execute goal on project kieserver-pull: Could not resolve dependencies for project org.openshift:kieserver-pull:jar:1.0.0.Final: Could not find artifact

**Comment by welshstew** [comment]
@jainmnsh you can get the image added into your environment by performing the following command: 

> oc import-image openshift/jboss-decisionserver64-openshift:1.3 --from=registry.access.redhat.com/jboss-decisionserver-6/decisionserver64-openshift:1.3 --confirm

However, following the README I get the same issue for hellorules:

Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openshift.quickstarts:decisionserver-hellorules:jar:1.3.0.Final in central (https://repo1.maven.org/maven2)
at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
... 27 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ERROR Aborting due to error code 1 from Maven build
Aborting due to error code 1 from maven kjar dependency pull
